/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NextInLineRouteImport } from './routes/next-in-line'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EditTokenRouteImport } from './routes/edit.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated/admin.countries'
import { Route as AuthenticatedAdminEditionsRouteImport } from './routes/_authenticated/admin.editions'
import { Route as AuthenticatedAdminRecoveryCodesRouteImport } from './routes/_authenticated/admin.recovery-codes'
import { Route as AuthenticatedAdminResponsesRouteImport } from './routes/_authenticated/admin.responses'
import { Route as AuthenticatedAdminRoundsRouteImport } from './routes/_authenticated/admin.rounds'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminResponsesIndexRouteImport } from './routes/_authenticated/admin.responses.index'
import { Route as AuthenticatedAdminResponsesIdRouteImport } from './routes/_authenticated/admin.responses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NextInLineRoute = NextInLineRouteImport.update({
  id: '/next-in-line',
  path: '/next-in-line',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EditTokenRoute = EditTokenRouteImport.update({
  id: '/edit/$token',
  path: '/edit/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEditionsRoute =
  AuthenticatedAdminEditionsRouteImport.update({
    id: '/editions',
    path: '/editions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecoveryCodesRoute =
  AuthenticatedAdminRecoveryCodesRouteImport.update({
    id: '/recovery-codes',
    path: '/recovery-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResponsesRoute =
  AuthenticatedAdminResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoundsRoute =
  AuthenticatedAdminRoundsRouteImport.update({
    id: '/rounds',
    path: '/rounds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResponsesIndexRoute =
  AuthenticatedAdminResponsesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminResponsesRoute,
  } as any)
const AuthenticatedAdminResponsesIdRoute =
  AuthenticatedAdminResponsesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminResponsesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/next-in-line': typeof NextInLineRoute
  '/recover': typeof RecoverRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/edit/$token': typeof EditTokenRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/editions': typeof AuthenticatedAdminEditionsRoute
  '/admin/recovery-codes': typeof AuthenticatedAdminRecoveryCodesRoute
  '/admin/responses': typeof AuthenticatedAdminResponsesRouteWithChildren
  '/admin/rounds': typeof AuthenticatedAdminRoundsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/responses/$id': typeof AuthenticatedAdminResponsesIdRoute
  '/admin/responses/': typeof AuthenticatedAdminResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/next-in-line': typeof NextInLineRoute
  '/recover': typeof RecoverRoute
  '/edit/$token': typeof EditTokenRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/editions': typeof AuthenticatedAdminEditionsRoute
  '/admin/recovery-codes': typeof AuthenticatedAdminRecoveryCodesRoute
  '/admin/rounds': typeof AuthenticatedAdminRoundsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/responses/$id': typeof AuthenticatedAdminResponsesIdRoute
  '/admin/responses': typeof AuthenticatedAdminResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/next-in-line': typeof NextInLineRoute
  '/recover': typeof RecoverRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/edit/$token': typeof EditTokenRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/admin/editions': typeof AuthenticatedAdminEditionsRoute
  '/_authenticated/admin/recovery-codes': typeof AuthenticatedAdminRecoveryCodesRoute
  '/_authenticated/admin/responses': typeof AuthenticatedAdminResponsesRouteWithChildren
  '/_authenticated/admin/rounds': typeof AuthenticatedAdminRoundsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/responses/$id': typeof AuthenticatedAdminResponsesIdRoute
  '/_authenticated/admin/responses/': typeof AuthenticatedAdminResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/next-in-line'
    | '/recover'
    | '/admin'
    | '/edit/$token'
    | '/admin/calendar'
    | '/admin/countries'
    | '/admin/editions'
    | '/admin/recovery-codes'
    | '/admin/responses'
    | '/admin/rounds'
    | '/admin/settings'
    | '/admin/'
    | '/admin/responses/$id'
    | '/admin/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/next-in-line'
    | '/recover'
    | '/edit/$token'
    | '/admin/calendar'
    | '/admin/countries'
    | '/admin/editions'
    | '/admin/recovery-codes'
    | '/admin/rounds'
    | '/admin/settings'
    | '/admin'
    | '/admin/responses/$id'
    | '/admin/responses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/next-in-line'
    | '/recover'
    | '/_authenticated/admin'
    | '/edit/$token'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/countries'
    | '/_authenticated/admin/editions'
    | '/_authenticated/admin/recovery-codes'
    | '/_authenticated/admin/responses'
    | '/_authenticated/admin/rounds'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/responses/$id'
    | '/_authenticated/admin/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NextInLineRoute: typeof NextInLineRoute
  RecoverRoute: typeof RecoverRoute
  EditTokenRoute: typeof EditTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-in-line': {
      id: '/next-in-line'
      path: '/next-in-line'
      fullPath: '/next-in-line'
      preLoaderRoute: typeof NextInLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/edit/$token': {
      id: '/edit/$token'
      path: '/edit/$token'
      fullPath: '/edit/$token'
      preLoaderRoute: typeof EditTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/countries': {
      id: '/_authenticated/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/editions': {
      id: '/_authenticated/admin/editions'
      path: '/editions'
      fullPath: '/admin/editions'
      preLoaderRoute: typeof AuthenticatedAdminEditionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recovery-codes': {
      id: '/_authenticated/admin/recovery-codes'
      path: '/recovery-codes'
      fullPath: '/admin/recovery-codes'
      preLoaderRoute: typeof AuthenticatedAdminRecoveryCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/responses': {
      id: '/_authenticated/admin/responses'
      path: '/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AuthenticatedAdminResponsesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rounds': {
      id: '/_authenticated/admin/rounds'
      path: '/rounds'
      fullPath: '/admin/rounds'
      preLoaderRoute: typeof AuthenticatedAdminRoundsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/responses/': {
      id: '/_authenticated/admin/responses/'
      path: '/'
      fullPath: '/admin/responses/'
      preLoaderRoute: typeof AuthenticatedAdminResponsesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminResponsesRoute
    }
    '/_authenticated/admin/responses/$id': {
      id: '/_authenticated/admin/responses/$id'
      path: '/$id'
      fullPath: '/admin/responses/$id'
      preLoaderRoute: typeof AuthenticatedAdminResponsesIdRouteImport
      parentRoute: typeof AuthenticatedAdminResponsesRoute
    }
  }
}

interface AuthenticatedAdminResponsesRouteChildren {
  AuthenticatedAdminResponsesIdRoute: typeof AuthenticatedAdminResponsesIdRoute
  AuthenticatedAdminResponsesIndexRoute: typeof AuthenticatedAdminResponsesIndexRoute
}

const AuthenticatedAdminResponsesRouteChildren: AuthenticatedAdminResponsesRouteChildren =
  {
    AuthenticatedAdminResponsesIdRoute: AuthenticatedAdminResponsesIdRoute,
    AuthenticatedAdminResponsesIndexRoute:
      AuthenticatedAdminResponsesIndexRoute,
  }

const AuthenticatedAdminResponsesRouteWithChildren =
  AuthenticatedAdminResponsesRoute._addFileChildren(
    AuthenticatedAdminResponsesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminEditionsRoute: typeof AuthenticatedAdminEditionsRoute
  AuthenticatedAdminRecoveryCodesRoute: typeof AuthenticatedAdminRecoveryCodesRoute
  AuthenticatedAdminResponsesRoute: typeof AuthenticatedAdminResponsesRouteWithChildren
  AuthenticatedAdminRoundsRoute: typeof AuthenticatedAdminRoundsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
  AuthenticatedAdminEditionsRoute: AuthenticatedAdminEditionsRoute,
  AuthenticatedAdminRecoveryCodesRoute: AuthenticatedAdminRecoveryCodesRoute,
  AuthenticatedAdminResponsesRoute:
    AuthenticatedAdminResponsesRouteWithChildren,
  AuthenticatedAdminRoundsRoute: AuthenticatedAdminRoundsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NextInLineRoute: NextInLineRoute,
  RecoverRoute: RecoverRoute,
  EditTokenRoute: EditTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
